lab6_3/Controllers/FileManagerController.cs
using lab6.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Threading.Tasks;


namespace lab6.Controllers
{
    public class FileManagerController : Controller
    {
        private readonly ForumContext _db;
        public FileManagerController(ForumContext context)
        {
            _db = context;
        }

        [HttpPost]
        [Route("/FileManager/AttachToTopic/{TopicId}")]
        public async Task<IActionResult> AttachToTopic(int TopicId, IFormFile file)
        {
            // загружаем картинку
            if (file != null)
            {
                TopicModel model = await _db.Topics
                    .Include(p => p.Pictures)
                    .FirstOrDefaultAsync(i => i.Id == TopicId);


                if (model.PictureCount < 3)
                {
                    byte[] img = null;
                    string picName = string.Concat(Guid.NewGuid().ToString());
                    using (var biReader = new BinaryReader(file.OpenReadStream()))
                    {
                        img = biReader.ReadBytes((int)file.Length);
                    }

                    model.Pictures.Add(new PictureModel
                    {
                        Name = picName,
                        Image = img
                    });
                    model.PictureCount++;
                    model.DateEdited = DateTime.Now;

                    await _db.SaveChangesAsync();

                    return RedirectToAction("OpenTopic", "SingleForum", new { TopicId });
                }
            }
            return RedirectToAction("OpenTopic", "SingleForum", new { TopicId });
        }

        [HttpPost]
        [Route("/FileManager/AttachToReply/{ReplyId}")]
        public async Task<IActionResult> AttachToReply(int ReplyId, IFormFile file)
        {
            int? TopicId = null;

            // загружаем картинку
            if (file != null)
            {
                ReplyModel model = await _db.Replies
                    .Include(p => p.Pictures)
                    .FirstOrDefaultAsync(i => i.Id == ReplyId);

                TopicId = model.TopicId;

                if (model.PictureCount < 3)
                {
                    byte[] img = null;
                    string picName = string.Concat(Guid.NewGuid().ToString());
                    using (var biReader = new BinaryReader(file.OpenReadStream()))
                    {
                        img = biReader.ReadBytes((int)file.Length);
                    }

                    model.Pictures.Add(new PictureModel
                    {
                        Name = picName,
                        Image = img
                    });
                    model.PictureCount++;
                    model.DateEdited = DateTime.Now;

                    await _db.SaveChangesAsync();

                    return RedirectToAction("OpenTopic", "SingleForum", new { model.TopicId });
                }
            }
            return RedirectToAction("OpenTopic", "SingleForum", new { TopicId });
        }

        public async Task<IActionResult> DetachFromTopic(int TopicId, string PictureName)
        {

            TopicModel topic = await _db.Topics.Include(p => p.Pictures).FirstOrDefaultAsync(i => i.Id == TopicId);
            PictureModel pic = await _db.Pictures.FirstOrDefaultAsync(p => p.Name == PictureName);
            topic.Pictures.Remove(pic);
            topic.PictureCount--;
            topic.DateEdited = DateTime.Now;

            _db.Pictures.Remove(pic);
            await _db.SaveChangesAsync();

            return RedirectToAction("OpenTopic", "SingleForum", routeValues: new { TopicId });
        }

        public async Task<IActionResult> DetachFromReply(int ReplyId, string PictureName)
        {

            ReplyModel reply = await _db.Replies.Include(p => p.Pictures).FirstOrDefaultAsync(i => i.Id == ReplyId);
            PictureModel pic = await _db.Pictures.FirstOrDefaultAsync(p => p.Name == PictureName);
            reply.Pictures.Remove(pic);
            reply.PictureCount--;
            reply.DateEdited = DateTime.Now;

            _db.Pictures.Remove(pic);
            await _db.SaveChangesAsync();

            return RedirectToAction("OpenTopic", "SingleForum", new { reply.TopicId });
        }
    }
}

lab6_3/Controllers/ForumCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using lab6.Models;
using Microsoft.EntityFrameworkCore;

namespace lab6.Controllers
{
    public class ForumCategoryController : Controller
    {

        private readonly ForumContext _db;
        public ForumCategoryController(ForumContext context)
        {
            _db = context;
        }


        public async Task<IActionResult> Index()
        {
            return View(await _db.ForumCategories.ToListAsync());
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ForumCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                _db.ForumCategories.Add(new ForumCategoryModel
                {
                    Name = model.Name,
                    Description = model.Description
                });
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }



        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                ForumCategoryModel model = await _db.ForumCategories.FirstOrDefaultAsync(p => p.Id == id);
                if (model != null)
                {
                    return View(model);
                }
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ForumCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                _db.ForumCategories.Update(model);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }




        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                ForumCategoryModel model = await _db.ForumCategories.FirstOrDefaultAsync(p => p.Id == id);
                return View(model);
            }
            return NotFound();
        }



        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                ForumCategoryModel model = await _db.ForumCategories.FirstOrDefaultAsync(p => p.Id == id);
                if (model != null)
                    return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                ForumCategoryModel model = await _db.ForumCategories
                    .Include(t => (t.Topics as TopicModel).Replies)
                    .ThenInclude(t => t.Pictures)
                    .Include(t => (t.Topics as TopicModel).Pictures)
                    .Include(t => t.Topics)
                    .FirstOrDefaultAsync(p => p.Id == id);
                if (model != null)
                {
                    _db.DeleteForumCategory(model);
                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
    }
}

lab6_3/Controllers/ReplyController.cs
using lab6.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace lab6.Controllers
{
    public class ReplyController : Controller
    {
        private readonly ForumContext _db;
        public ReplyController(ForumContext context)
        {
            _db = context;
        }


        [Authorize]
        [HttpGet]
        public IActionResult Create(int TopicId, int UserId)
        {
            ViewBag.tid = TopicId;
            ViewBag.uid = UserId;
            return View();
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(ReplyModel model)
        {
            if (ModelState.IsValid)
            {
                ReplyModel reply = new()
                {
                    Text = model.Text,
                    DateCreated = model.DateCreated,
                    DateEdited = model.DateEdited,
                    TopicId = model.TopicId,
                    AuthorId = model.AuthorId,
                    PictureCount = model.PictureCount
                };
                TopicModel topic = await _db.Topics.FirstOrDefaultAsync(i => i.Id == model.TopicId);

                topic.Replies.Add(reply);
                topic.ReplyCount++;
                await _db.SaveChangesAsync();

                topic.LastReplyId = reply.Id;

                await _db.SaveChangesAsync();
                return RedirectToAction("OpenTopic", "SingleForum", new { model.TopicId });
            }
            return View(model);
        }


        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Edit(int? ReplyId)
        {
            if (ReplyId != null)
            {
                ReplyModel reply = await _db.Replies.FirstOrDefaultAsync(p => p.Id == ReplyId);
                if (reply != null)
                {
                    return View(reply);
                }
            }
            return NotFound();
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(ReplyModel model)
        {
            if (ModelState.IsValid)
            {
                _db.Replies.Update(model);
                await _db.SaveChangesAsync();
                return RedirectToAction("OpenTopic", "SingleForum", new { model.TopicId });
            }
            return View(model);
        }


        [Authorize]
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? ReplyId)
        {
            if (ReplyId != null)
            {
                ReplyModel model = await _db.Replies
                    .Include(t => t.Topic)
                    .Include(o => o.Author)
                    .FirstOrDefaultAsync(p => p.Id == ReplyId);
                if (model != null)
                    return View(model);
            }
            return NotFound();
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Delete(int? ReplyId)
        {
            if (ReplyId != null)
            {         
                ReplyModel reply = await _db.Replies.Include(p => p.Pictures).FirstOrDefaultAsync(i => i.Id == ReplyId);
                TopicModel topic = await _db.Topics.FirstOrDefaultAsync(i => i.Id == reply.TopicId);


                _db.DeleteReply(reply, topic);

                await _db.SaveChangesAsync();

                return RedirectToAction("OpenTopic", "SingleForum", new { TopicId = topic.Id });
            }
            return NotFound();
        }
    }
}

lab6_3/Controllers/SingleForumController.cs
using lab6.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace lab6.Controllers
{
    public class SingleForumController : Controller
    {

        private readonly ForumContext _db;
        public SingleForumController(ForumContext context)
        {
            _db = context;
        }

        public IActionResult PreIndex(int FId)
        {
            HttpContext.Session.SetInt32("fid", FId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Index()
        {
            int? fid = HttpContext.Session.GetInt32("fid");

            if (fid != null)
            {
                return View(await _db.ForumCategories
                    .Include(t => ((t.Topics as TopicModel).Author))
                    .Include(t => ((t.Topics as TopicModel).Replies as ReplyModel).Author)
                    .FirstOrDefaultAsync(m => m.Id == fid));
            }
            return NotFound();
        }

        
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.fid = HttpContext.Session.GetInt32("fid");
            return View();
        }  
        [HttpPost]
        public async Task<IActionResult> Create(TopicModel model)
        {
            if (ModelState.IsValid)
            {
                _db.Topics.Add(new TopicModel
                {
                    Title = model.Title,
                    Description = model.Description,
                    ForumId = model.ForumId,
                    AuthorId = model.AuthorId,
                    DateCreated = model.DateCreated,
                    ReplyCount = model.ReplyCount
                });
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                TopicModel topic = await _db.Topics.FirstOrDefaultAsync(p => p.Id == id);
                if (topic != null)
                {
                    return View(topic);
                }
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(TopicModel model)
        {
            if (ModelState.IsValid)
            {
                _db.Topics.Update(model);
                await _db.SaveChangesAsync();
                return RedirectToAction("OpenTopic", new { TopicId = model.Id });
            }
            return View(model);
        }


        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                TopicModel model = await _db.Topics
                    .Include(t => t.Forum)
                    .Include(o => o.Author)
                    .FirstOrDefaultAsync(p => p.Id == id);
                if (model != null)
                    return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                TopicModel model = await _db.Topics
                    .Include(r => r.Replies)
                    .Include(r => (r.Replies as ReplyModel).Pictures)
                    .Include(p => p.Pictures)
                    .FirstOrDefaultAsync(p => p.Id == id);

                if (model != null)
                {
                    _db.DeleteTopic(model);

                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }


        [HttpGet]
        public async Task<IActionResult> OpenTopic(int TopicId, int? ForumId)
        {
            if(ForumId != null)
            {
                HttpContext.Session.SetInt32("fid", (int)ForumId);
            }

            TopicModel topic = await _db.Topics
            .Include(r => (r.Replies as ReplyModel).Author)
            .Include(r => (r.Replies as ReplyModel).Pictures)
            .Include(a => a.Author)
            .Include(f => f.Forum)
            .Include(p => p.Pictures)
            .FirstOrDefaultAsync(i => i.Id == TopicId);
            if (topic != null)
            {
                return View(topic);
            }
            return NotFound();
        }

    }
}

lab6_3/Views/SingleForum/Create.cshtml
@model lab6.Models.TopicModel

@{
    ViewData["Title"] = "Create Topic";
    var user = Context.User;
    var UserId = user.Claims.First().Value;
    DateTime dt = DateTime.Now;
}
<h3>Create</h3>
<hr />
<div>
    <div>
        <form asp-controller="SingleForum" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div>
                <h1><label asp-for="Title" class="control-label"></label></h1>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <br />
            <div class="card">
                <div class="card-header">
                    <span>*username* // *creation date* // *edit date*</span>
                </div>
                <div class="card-body">
                    <h1><label>Content </label></h1>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <input hidden asp-for="ReplyCount" class="form-control" value="0" />
            </div>
            <div class="form-group">
                <input hidden asp-for="LastReplyId" class="form-control" value="null" />
            </div>
            <div class="form-group">
                <input hidden asp-for="DateCreated" class="form-control" value="@dt.ToString("dddd, dd MMMM yyyy HH:mm:ss")" />
            </div>
            <div class="form-group">
                <input hidden asp-for="ForumId" class="form-control" value="@ViewBag.fid" />
            </div>
            <div class="form-group">
                <input hidden asp-for="AuthorId" class="form-control" value="@UserId" />
            </div>
            <div class="form-group">
                <a asp-action="Index" asp-route-FId="@ViewBag.fid">Back to List</a><input type="submit" value="Create Topic" class="btn btn-primary" style="margin: 0 0 0 15px;" />
            </div>
        </form>
    </div>
</div>

lab6_3/Views/SingleForum/Delete.cshtml
@model lab6.Models.TopicModel

@{
    ViewData["Title"] = "Delete Topic";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>All replies will be delited with the topic.</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            <span>Replies</span>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReplyCount)
        </dd>
        <dt class = "col-sm-2">
            <span class="font-weight-bold">Forum Category</span>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Forum.Name)
        </dd>
        <dt class = "col-sm-2">
            <span class="font-weight-bold">Topic Creator</span>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back</a>
    </form>
</div>

lab6_3/Views/SingleForum/Edit.cshtml
@model lab6.Models.TopicModel

@{
    ViewData["Title"] = "Edit Topic";
}

<h3>Edit</h3>
<hr />
<div>
    <div>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div>
                <h1><label asp-for="Title" class="control-label"></label></h1>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <br />
            <div class="card">
                <div class="card-header">
                    <span>*username* // *creation date* // *edit date*</span>
                </div>
                <div class="card-body">
                    <h1><label>Content </label></h1>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <input hidden asp-for="DateCreated" class="form-control" value="@Model.DateCreated" />
            </div>
            <div class="form-group">
                <input hidden asp-for="ForumId" class="form-control" value="@Model.ForumId" />
            </div>
            <div class="form-group">
                <input hidden asp-for="AuthorId" class="form-control" value="@Model.AuthorId" />
            </div>
            <div class="form-group">
                <a asp-action="OpenTopic" asp-route-TopicId="@Model.Id">Back</a><input type="submit" value="Save" class="btn btn-primary" style="margin: 0 0 0 15px;" />
            </div>
        </form>
    </div>
</div>

lab6_3/Views/SingleForum/Index.cshtml
@using lab6.Models
@model ForumCategoryModel

@{
    ViewData["Title"] = "Forum";
    var user = Context.User;
}

<h1>@Model.Name</h1>
<h5>@Model.Description</h5>

@if (user.Identity.IsAuthenticated)
{
    <p>
        <a asp-action="Create" asp-route-FId="">Create New Topic</a><span>   |   <a asp-controller="ForumCategory" asp-action="Index">Back To Forum Categories</a></span>
    </p>
}
else
{
    <span><a asp-controller="ForumCategory" asp-action="Index">Back</a></span>
    <br />
}
<br />

<table class="table table-bordered table-striped">
    @foreach (var item in Model.Topics)
    {
        <tr>
            <td class="align-middle">
                <h5><a asp-action="OpenTopic" asp-route-TopicId="@item.Id">@Html.DisplayFor(modelItem => item.Title)</a></h5>            
                <div><span class="font-weight-bold">Created by: </span> @Html.DisplayFor(modelItem => item.Author.Email)</div>
                <div><span class="font-weight-bold">Creation date: </span> @Html.DisplayFor(modelItem => item.DateCreated)</div>
            </td>
            <td class="align-middle">
                <div><span class="font-weight-bold">Replies:</span> @Html.DisplayFor(modelItem => item.ReplyCount)</div>
                @if (user.Identity.IsAuthenticated)
                {
                    @if (user.HasClaim("RoleId", "1") || item.Author.Email == user.Identity.Name)
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) <text> | </text>
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id });
                    }
                }
            </td>
            <td class="align-middle">
                @if (item.ReplyCount == 0)
                {
                    <div><span class="font-weight-bold">Last reply: no replies</span></div>
                }
                else
                {
                    @if (item.LastReplyId == null)
                    {
                        <div><span class="font-weight-bold">Last reply: deleted</span></div>
                    }
                    else
                    {
                        <div><span class="font-weight-bold">Last reply: @Html.DisplayFor(modelItem => item.Replies.FirstOrDefault(r => r.Id == item.LastReplyId).Author.Email)</span></div>
                        <div><span class="font-weight-bold">at: </span> @Html.DisplayFor(modelItem => item.Replies.FirstOrDefault(r => r.Id == item.LastReplyId).DateEdited)</div>
                    }
                }
            </td>
        </tr>
    }
</table>

lab6_3/Views/SingleForum/OpenTopic.cshtml
@model lab6.Models.TopicModel

@{
    ViewData["Title"] = "Topic";
    var user = Context.User;
    var dateEdited = Model.DateEdited.ToString("dddd, dd MMMM yyyy HH:mm:ss");
}

<h1>@Model.Title</h1>
<div>
    @if (user.Identity.IsAuthenticated)
    {
        <a asp-controller="Reply" asp-action="Create" 
           asp-route-TopicId="@Model.Id" 
           asp-route-UserId="@user.Claims.First().Value">Reply</a> <text> | </text>
        @if (user.HasClaim("RoleId", "1") || Model.Author.Email == user.Identity.Name)
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) <text> | </text>
            @Html.ActionLink("Delete", "Delete", new { id = Model.Id }); <text> | </text>
        }
    }
    <a asp-action="Index">Back to @Model.Forum.Name Category</a>
</div>
@Html.ValidationSummary()
<br />
<div class="card">
    <div class="card-header">
        @Html.DisplayFor(item => item.Author.Email), @Model.DateCreated (edited: @dateEdited)
        @if (user.Identity.IsAuthenticated)
        {
            @if ((user.HasClaim("RoleId", "1")
               || Model.Author.Email == user.Identity.Name)
               && Model.PictureCount < 3)
            {
                <input type="button" id="attc" onclick="attachToTopic(@Model.Id)"
                       value="Attach" class="col-md-1 btn btn-outline-primary btn-sm"
                       style="margin-left:24px;width: 120px;height:24px;font-size:12px;" />
            }
        }
    </div>

    <div class="card-body">
        @Html.DisplayFor(item => item.Description)

        <div class="card-columns mt-3">
           @if (Model.PictureCount > 0)
            {
               @foreach (var picture in Model.Pictures)
                {
            <div class="card p-1 bg-light">
                @Html.Raw("<img class=\"card-img-top\" src=\"data:image/jpeg;base64,"
               + Convert.ToBase64String(picture.Image) + "\" alt=\"@picture.Name\" />")

                <div class="card-footer bg-light m-0">
                    @if ((user.HasClaim("RoleId", "1") || Model.Author.Email == user.Identity.Name))
                    {
                        <a asp-controller="FileManager" asp-action="DetachFromTopic" asp-route-TopicId="@Model.Id"
                           asp-route-PictureName="@picture.Name"
                           class="btn btn-outline-danger btn-sm"
                           style="width:100%;height:29px;">Delete</a>
                    } 
                </div>
            </div>
                }
            }
        </div>
    </div>
    <div class="PictureUpload"></div>
</div>

<div class="replies">
    @if (Model.Replies.Any())
    {
        <h4 class="font-weight-bold mt-4">Replies</h4>
        @foreach (var reply in Model.Replies)
        {
            <div class="card mt-3 mb-3">
                <div class="card-header">
                    @reply.Author.Email, @reply.DateCreated (edited: @reply.DateEdited.ToString("dddd, dd MMMM yyyy HH:mm:ss"))
                    @if (user.Identity.IsAuthenticated)
                    {
                        @if (user.HasClaim("RoleId", "1") || reply.Author.Email == user.Identity.Name)
                        {
                            @Html.ActionLink("Edit", "Edit", "Reply", new { ReplyId = @reply.Id },
                             new{ @class = "col-md-1 btn btn-outline-primary btn-sm",
                             @style = "margin-left:12px;width:120px;height:24px;font-size:12px;"})

                             @Html.ActionLink("Delete", "Delete", "Reply", new { ReplyId = @reply.Id },
                              new { @class="col-md-1 btn btn-outline-primary btn-sm",
                              @style="margin-left:12px;width: 120px;height:24px;font-size:12px;"})

                            @if (reply.PictureCount < 3) 
                            {
                                <input type="button" id="attc" onclick="attachToReply(@reply.Id)" value="Attach"
                                       class="col-md-1 btn btn-outline-primary btn-sm" style="margin-left: 8px;
                                       width: 120px;height:24px;font-size:12px;" />
                            }
                        }
                    }
                </div>

                <div class="card-body">
                    @reply.Text

                    <div class="card-columns mt-3">
                        @if (reply.PictureCount > 0)
                        {
                            @foreach (var picture in reply.Pictures)
                            {
                                <div class="card p-1 bg-light">
                                    @Html.Raw("<img class=\"card-img-top\" src=\"data:image/jpeg;base64,"
                                   + Convert.ToBase64String(picture.Image) + "\" alt=\"@picture.Name\" style=\"max-height:400px;\" />")

                                    <div class="card-footer bg-light m-0">
                                        @if ((user.HasClaim("RoleId", "1") || reply.Author.Email == user.Identity.Name))
                                        {
                                            <a asp-controller="FileManager" asp-action="DetachFromReply" asp-route-ReplyId="@reply.Id"
                                               asp-route-PictureName="@picture.Name"
                                               class="btn btn-outline-danger btn-sm"
                                               style="width:100%;height:29px;">Delete</a>
                                        }
                                    </div>
                                </div>
                            }
                        }
                    </div>

                </div>
            </div>
        }

    }
    else
    {
        @if (user.Identity.IsAuthenticated && (user.Identity.Name != Model.Author.Email))
         {
            <div class="text-lg-center font-italic mt-4">Be first to start the discussion.</div>
         }

}
</div>



<script src="~/js/uploadFile.js" type="text/javascript"></script>