lab6_3/Controllers/ForumCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using lab6.Models;
using Microsoft.EntityFrameworkCore;

namespace lab6.Controllers
{
    public class ForumCategoryController : Controller
    {

        private readonly ForumContext _db;
        public ForumCategoryController(ForumContext context)
        {
            _db = context;
        }


        public async Task<IActionResult> Index()
        {
            return View(await _db.ForumCategories.ToListAsync());
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ForumCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                _db.ForumCategories.Add(new ForumCategoryModel
                {
                    Name = model.Name,
                    Description = model.Description
                });
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }



        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                ForumCategoryModel model = await _db.ForumCategories.FirstOrDefaultAsync(p => p.Id == id);
                if (model != null)
                {
                    return View(model);
                }
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ForumCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                _db.ForumCategories.Update(model);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }




        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                ForumCategoryModel model = await _db.ForumCategories.FirstOrDefaultAsync(p => p.Id == id);
                return View(model);
            }
            return NotFound();
        }



        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                ForumCategoryModel model = await _db.ForumCategories.FirstOrDefaultAsync(p => p.Id == id);
                if (model != null)
                    return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                ForumCategoryModel model = await _db.ForumCategories
                    .Include(t => (t.Topics as TopicModel).Replies)
                    .ThenInclude(t => t.Pictures)
                    .Include(t => (t.Topics as TopicModel).Pictures)
                    .Include(t => t.Topics)
                    .FirstOrDefaultAsync(p => p.Id == id);
                if (model != null)
                {
                    _db.DeleteForumCategory(model);
                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
    }
}

lab6_3/Controllers/SingleForumController.cs
using lab6.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace lab6.Controllers
{
    public class SingleForumController : Controller
    {

        private readonly ForumContext _db;
        public SingleForumController(ForumContext context)
        {
            _db = context;
        }

        public IActionResult PreIndex(int FId)
        {
            HttpContext.Session.SetInt32("fid", FId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Index()
        {
            int? fid = HttpContext.Session.GetInt32("fid");

            if (fid != null)
            {
                return View(await _db.ForumCategories
                    .Include(t => ((t.Topics as TopicModel).Author))
                    .Include(t => ((t.Topics as TopicModel).Replies as ReplyModel).Author)
                    .FirstOrDefaultAsync(m => m.Id == fid));
            }
            return NotFound();
        }

        
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.fid = HttpContext.Session.GetInt32("fid");
            return View();
        }  
        [HttpPost]
        public async Task<IActionResult> Create(TopicModel model)
        {
            if (ModelState.IsValid)
            {
                _db.Topics.Add(new TopicModel
                {
                    Title = model.Title,
                    Description = model.Description,
                    ForumId = model.ForumId,
                    AuthorId = model.AuthorId,
                    DateCreated = model.DateCreated,
                    ReplyCount = model.ReplyCount
                });
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                TopicModel topic = await _db.Topics.FirstOrDefaultAsync(p => p.Id == id);
                if (topic != null)
                {
                    return View(topic);
                }
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(TopicModel model)
        {
            if (ModelState.IsValid)
            {
                _db.Topics.Update(model);
                await _db.SaveChangesAsync();
                return RedirectToAction("OpenTopic", new { TopicId = model.Id });
            }
            return View(model);
        }


        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                TopicModel model = await _db.Topics
                    .Include(t => t.Forum)
                    .Include(o => o.Author)
                    .FirstOrDefaultAsync(p => p.Id == id);
                if (model != null)
                    return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                TopicModel model = await _db.Topics
                    .Include(r => r.Replies)
                    .Include(r => (r.Replies as ReplyModel).Pictures)
                    .Include(p => p.Pictures)
                    .FirstOrDefaultAsync(p => p.Id == id);

                if (model != null)
                {
                    _db.DeleteTopic(model);

                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }


        [HttpGet]
        public async Task<IActionResult> OpenTopic(int TopicId, int? ForumId)
        {
            if(ForumId != null)
            {
                HttpContext.Session.SetInt32("fid", (int)ForumId);
            }

            TopicModel topic = await _db.Topics
            .Include(r => (r.Replies as ReplyModel).Author)
            .Include(r => (r.Replies as ReplyModel).Pictures)
            .Include(a => a.Author)
            .Include(f => f.Forum)
            .Include(p => p.Pictures)
            .FirstOrDefaultAsync(i => i.Id == TopicId);
            if (topic != null)
            {
                return View(topic);
            }
            return NotFound();
        }

    }
}

lab6_3/Views/ForumCategory/Create.cshtml
@model lab6.Models.ForumCategoryModel

@{
    ViewData["Title"] = "Create Category";
}

<h1>Create</h1>

<h4>Forum Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea  asp-for="Description" class="form-control" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

lab6_3/Views/ForumCategory/Delete.cshtml
@model lab6.Models.ForumCategoryModel

@{
    ViewData["Title"] = "Delete Category";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Forum Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

lab6_3/Views/ForumCategory/Details.cshtml
@model lab6.Models.ForumCategoryModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Forum Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

lab6_3/Views/ForumCategory/Edit.cshtml
@model lab6.Models.ForumCategoryModel

@{
    ViewData["Title"] = "Edit Category";
}

<h1>Edit</h1>

<h4>Forum Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

lab6_3/Views/ForumCategory/Index.cshtml
@model IEnumerable<lab6.Models.ForumCategoryModel>

@{
    ViewData["Title"] = "Categories";
    var user = Context.User;
}


<h1>All Forum Categories</h1>


@if (user.Identity.IsAuthenticated && user.HasClaim("RoleId", "1"))
{
    <p>
        <a asp-action="Create">Create New Category</a>
    </p>
}
<br />
@if (Model.Count<ForumCategoryModel>() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="table-hover">
                    <td style="width: 15%;">
                        <a asp-controller="SingleForum" asp-action="PreIndex" asp-route-FId="@item.Id"> @Html.DisplayFor(modelItem => item.Name) </a>
                    </td>
                    <td style="">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td style="width: 180px;">
                        @if (user.Identity.IsAuthenticated)
                        {
                            @if (user.HasClaim("RoleId", "1"))
                            {
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) <text> | </text>
                            }
                            @Html.ActionLink("Details", "Details", new { id = item.Id })
                            @if (user.HasClaim("RoleId", "1"))
                            {
                                <text> | </text> @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                            }

                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Forum doesn't contain any category yet! :(</p>
}